spring:
  application:
    name: booking-service

  data:
    mongodb:
      uri: ${MONGO_URI}
    redis:
      url: ${REDIS_URL}


  cache:
    type: redis

logging:
  level:
    root: INFO

server:
  port: ${PORT:2019}

jwt:
  payment:
    secret: ${JWT_SECRET:120a815e74a9edf768ac8db1bf0de298ab694cf9b922afc45551eac4e0e7fd7a}
    expiry-minutes: 10

inventory:
  service:
    url: ${INVENTORY_SERVICE_URL}
    name: ${INVENTORY_SERVICE_NAME:inventory-service}
