spring:
  application:
    name: inventory-service
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/inventory_service_FMS
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 9090
internal:
  api-key: Z3Vuc3d1bmdwcmVzaWRlbnRzdHJhbmdlcmxhc3Rk